logo: /face.png
dark: false

# rss: /atom.xml
disqus:
google_analytics:

# Social accounts
pinterest:
twitter: chickenbellyfin
github: chickenbellyfinn
instagram: chickenbellyfinn
youtube: chickenbellyfinn
facebook:
linkedin:
